# Generated by Django 3.2 on 2023-05-04 13:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApi', '0002_alter_clinic_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
