# Generated by Django 3.2 on 2023-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApi', '0004_alter_address_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
